"""Capture ownership, immutable upload reservations, verified chunks and sealed manifests."""
from alembic import op
import sqlalchemy as sa

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('capture_epoch', sa.Integer(), nullable=False),
    sa.Column('lifecycle_epoch', sa.Integer(), nullable=False),
    sa.Column('audio_epoch', sa.Integer(), nullable=False),
    sa.Column('grant_hash', sa.String(length=64), nullable=False),
    sa.Column('grant_expires_at', sa.DateTime(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('recovery', sa.Boolean(), nullable=False),
    sa.Column('manifest_version', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=True),
    sa.Column('final_sample_count', sa.BigInteger(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('sample_rate >= 8000 AND sample_rate <= 192000', name='capture_sample_rate'),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'lecture_id'),
    sa.UniqueConstraint('lecture_id', 'capture_epoch')
    )
    op.create_index(op.f('ix_capture_runs_lecture_id'), 'capture_runs', ['lecture_id'], unique=False)
    op.create_table('audio_manifest_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'lecture_id'], ['capture_runs.id', 'capture_runs.lecture_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'version')
    )
    op.create_table('upload_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('identity', sa.JSON(), nullable=False),
    sa.Column('object_key', sa.String(length=240), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('sequence >= 0', name='reservation_sequence'),
    sa.ForeignKeyConstraint(['run_id', 'lecture_id'], ['capture_runs.id', 'capture_runs.lecture_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'lecture_id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('run_id', 'sequence')
    )
    op.create_index(op.f('ix_upload_reservations_lecture_id'), 'upload_reservations', ['lecture_id'], unique=False)
    op.create_table('audio_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id', 'lecture_id'], ['upload_reservations.id', 'upload_reservations.lecture_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_chunks_lecture_id'), 'audio_chunks', ['lecture_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrade is disabled; preserve captured audio and use a forward migration.")
