"""Versioned transcription, immutable evidence and speech attempt counts."""
from alembic import op
import sqlalchemy as sa

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('audio_epoch', sa.Integer(), nullable=False),
    sa.Column('manifests', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'lecture_id'),
    sa.UniqueConstraint('lecture_id', 'sequence')
    )
    op.create_index(op.f('ix_transcript_snapshots_lecture_id'), 'transcript_snapshots', ['lecture_id'], unique=False)
    op.create_table('speech_windows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('manifest_version', sa.Integer(), nullable=False),
    sa.Column('core_start', sa.BigInteger(), nullable=False),
    sa.Column('core_end', sa.BigInteger(), nullable=False),
    sa.Column('context_start', sa.BigInteger(), nullable=False),
    sa.Column('context_end', sa.BigInteger(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.CheckConstraint('context_start <= core_start AND core_start < core_end AND core_end <= context_end', name='speech_window_bounds'),
    sa.ForeignKeyConstraint(['run_id', 'lecture_id'], ['capture_runs.id', 'capture_runs.lecture_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'lecture_id'),
    sa.UniqueConstraint('run_id', 'manifest_version', 'core_start')
    )
    op.create_index(op.f('ix_speech_windows_lecture_id'), 'speech_windows', ['lecture_id'], unique=False)
    op.create_table('speech_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('window_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_token', sa.String(length=36), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['window_id', 'lecture_id'], ['speech_windows.id', 'speech_windows.lecture_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_token'),
    sa.UniqueConstraint('id', 'lecture_id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('window_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['window_id', 'lecture_id'], ['speech_windows.id', 'speech_windows.lecture_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'lecture_id'),
    sa.UniqueConstraint('window_id', 'position')
    )
    op.create_table('transcript_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=12000), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('start_sample', sa.BigInteger(), nullable=False),
    sa.Column('end_sample', sa.BigInteger(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('start_sample >= 0 AND end_sample > start_sample', name='transcript_span'),
    sa.ForeignKeyConstraint(['generation_id', 'lecture_id'], ['speech_generations.id', 'speech_generations.lecture_id'], ),
    sa.ForeignKeyConstraint(['segment_id', 'lecture_id'], ['transcript_segments.id', 'transcript_segments.lecture_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'lecture_id'),
    sa.UniqueConstraint('segment_id', 'revision')
    )
    op.create_table('transcript_snapshot_items',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id', 'lecture_id'], ['transcript_snapshots.id', 'transcript_snapshots.lecture_id'], ),
    sa.ForeignKeyConstraint(['version_id', 'lecture_id'], ['transcript_versions.id', 'transcript_versions.lecture_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id', 'position')
    )
    op.add_column('jobs', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrade is disabled; preserve transcript evidence and use a forward migration.")
